spring:
  datasource:
    driver-calss-name: com.mysql.cj.jdbc.Drive
    url: jdbc:mysql://localhost:3306/big_event?serverTimezone=UTC
    username: root
    password: lqz021215
  redis:
    host: localhost
    port: 6379



#  mybatis
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true  #开启驼峰命名与下划线命名转换

